name: Master Build

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - run: npm ci

    - run: npm run test
